// Command type constants
// These are the types of commands that can be executed

export const COMMAND_TYPES = {
  // Item commands
  ADD_ITEM: 'ADD_ITEM',
  BULK_ADD_ITEMS: 'BULK_ADD_ITEMS',
  REMOVE_ITEM: 'REMOVE_ITEM',
  SET_ITEM_PROPERTY: 'SET_ITEM_PROPERTY',
  SET_ITEM_ACTIVE: 'SET_ITEM_ACTIVE',
  SET_ITEM_INACTIVE: 'SET_ITEM_INACTIVE',
  
  // Notes commands
  ADD_ITEM_NOTE: 'ADD_ITEM_NOTE',
  UPDATE_ITEM_NOTE: 'UPDATE_ITEM_NOTE',
  DELETE_ITEM_NOTE: 'DELETE_ITEM_NOTE',
  
  // Confidence survey commands
  OPEN_CONFIDENCE_SURVEY: 'OPEN_CONFIDENCE_SURVEY',
  SUBMIT_CONFIDENCE_SURVEY: 'SUBMIT_CONFIDENCE_SURVEY',
  DELETE_CONFIDENCE_SURVEY: 'DELETE_CONFIDENCE_SURVEY',
  CANCEL_CONFIDENCE_SURVEY: 'CANCEL_CONFIDENCE_SURVEY',
  
  // Stage navigation commands
  NAVIGATE_TO_STAGE: 'NAVIGATE_TO_STAGE',
  ADVANCE_STAGE: 'ADVANCE_STAGE',
  BACK_STAGE: 'BACK_STAGE',
  SET_CURRENT_STAGE: 'SET_CURRENT_STAGE',
  
  // Bucket commands
  SET_URGENCY_LIMIT: 'SET_URGENCY_LIMIT',
  SET_VALUE_LIMIT: 'SET_VALUE_LIMIT',
  SET_URGENCY_WEIGHT: 'SET_URGENCY_WEIGHT',
  SET_VALUE_WEIGHT: 'SET_VALUE_WEIGHT',
  SET_DURATION_WEIGHT: 'SET_DURATION_WEIGHT',
  SET_URGENCY_TITLE: 'SET_URGENCY_TITLE',
  SET_URGENCY_DESCRIPTION: 'SET_URGENCY_DESCRIPTION',
  SET_VALUE_TITLE: 'SET_VALUE_TITLE',
  SET_VALUE_DESCRIPTION: 'SET_VALUE_DESCRIPTION',
  SET_DURATION_TITLE: 'SET_DURATION_TITLE',
  SET_DURATION_DESCRIPTION: 'SET_DURATION_DESCRIPTION',
  
  // App control commands
  CLEAR_ITEM_DATA_ONLY: 'CLEAR_ITEM_DATA_ONLY',
  CLEAR_ALL_DATA: 'CLEAR_ALL_DATA',
  START_APP: 'START_APP'
};

